/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List environments, newest first */
        get: operations["list-environments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an environment with its log streams */
        get: operations["get-environment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environments/{id}/destroy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Destroy an environment (admin) */
        post: operations["destroy-environment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environments/{id}/logs/{stream}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a log stream page (add follow=true for a live SSE stream) */
        get: operations["read-logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events in sequence order */
        get: operations["list-events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jobs, most recent first */
        get: operations["list-jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a job */
        get: operations["get-job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job steps and URL from GitHub */
        get: operations["get-job-github"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard summary */
        get: operations["get-overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scale-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scale sets */
        get: operations["list-scale-sets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration without secrets */
        get: operations["get-settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finished jobs per hour */
        get: operations["job-stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Alert: {
            environment_id?: string;
            kind: string;
            level: string;
            message: string;
            scale_set?: string;
            /** Format: date-time */
            time: string;
        };
        Capacity: {
            /** Format: double */
            disk_max_percent: number;
            /** Format: double */
            disk_percent: number;
            /** Format: int64 */
            environments_live: number;
            /** Format: int64 */
            environments_max: number;
            /** Format: int64 */
            host_memory_available_mb: number;
            /** Format: int64 */
            host_memory_total_mb: number;
            /** Format: int64 */
            memory_budget_mb: number;
            /** Format: int64 */
            memory_committed_mb: number;
        };
        Entry: {
            /** Format: int64 */
            offset: number;
            text: string;
            /** Format: date-time */
            time: string;
        };
        Environment: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Environment.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            exit_code?: number;
            failure_reason?: string;
            failure_stage?: string;
            id: string;
            ip?: string;
            job_id?: string;
            log_streams?: components["schemas"]["LogStream"][] | null;
            /** Format: int64 */
            memory_mb: number;
            /** Format: int64 */
            runner_id?: number;
            runner_name?: string;
            runtime_ref?: string;
            scale_set: string;
            state: string;
            /** Format: date-time */
            state_changed_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        Event: {
            data?: {
                [key: string]: unknown;
            };
            environment_id?: string;
            job_id?: string;
            kind: string;
            level: string;
            message: string;
            scale_set?: string;
            /** Format: int64 */
            seq: number;
            /** Format: date-time */
            time: string;
        };
        Job: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Job.json
             */
            readonly $schema?: string;
            display_name: string;
            environment_id?: string;
            event_name?: string;
            /** Format: date-time */
            finished_at: string;
            id: string;
            /** Format: date-time */
            queued_at: string;
            repository: string;
            result?: string;
            /** Format: int64 */
            run_id?: number;
            runner_name?: string;
            scale_set: string;
            /** Format: date-time */
            started_at: string;
            status: string;
            /** Format: date-time */
            updated_at: string;
            workflow_ref?: string;
        };
        "Job-statsResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Job-statsResponse.json
             */
            readonly $schema?: string;
            buckets: components["schemas"]["JobBucket"][] | null;
        };
        JobBucket: {
            /** Format: int64 */
            canceled: number;
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            other: number;
            /** Format: date-time */
            start: string;
            /** Format: int64 */
            succeeded: number;
        };
        JobDetails: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/JobDetails.json
             */
            readonly $schema?: string;
            available: boolean;
            conclusion?: string;
            /** Format: int64 */
            id?: number;
            reason?: string;
            status?: string;
            steps: components["schemas"]["Step"][] | null;
            url?: string;
        };
        KPIs: {
            /** Format: int64 */
            jobs_24h: number;
            /** Format: double */
            median_queue_seconds_24h: number;
            /** Format: int64 */
            running_jobs: number;
            /** Format: double */
            success_rate_24h: number;
            /** Format: int64 */
            waiting_demand: number;
        };
        "List-environmentsResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/List-environmentsResponse.json
             */
            readonly $schema?: string;
            environments: components["schemas"]["Environment"][] | null;
        };
        "List-eventsResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/List-eventsResponse.json
             */
            readonly $schema?: string;
            events: components["schemas"]["Event"][] | null;
        };
        "List-jobsResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/List-jobsResponse.json
             */
            readonly $schema?: string;
            jobs: components["schemas"]["Job"][] | null;
        };
        "List-scale-setsResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/List-scale-setsResponse.json
             */
            readonly $schema?: string;
            scale_sets: components["schemas"]["ScaleSet"][] | null;
        };
        LogStream: {
            /** Format: int64 */
            bytes: number;
            environment_id: string;
            /** Format: date-time */
            first_at: string;
            /** Format: date-time */
            last_at: string;
            /** Format: int64 */
            last_seq: number;
            /** Format: int64 */
            lines: number;
            stream: string;
        };
        Overview: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Overview.json
             */
            readonly $schema?: string;
            alerts: components["schemas"]["Alert"][] | null;
            capacity: components["schemas"]["Capacity"];
            kpis: components["schemas"]["KPIs"];
        };
        "Read-logsResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Read-logsResponse.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["Entry"][] | null;
            /** Format: int64 */
            next: number;
        };
        ScaleSet: {
            /** Format: int64 */
            desired: number;
            /** Format: int64 */
            github_id: number;
            listen_error?: string;
            listening: boolean;
            /** Format: int64 */
            live: number;
            name: string;
            waiting?: string;
            /** Format: date-time */
            waiting_since: string;
        };
        Settings: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/Settings.json
             */
            readonly $schema?: string;
            admin_actions: boolean;
            capacity: {
                [key: string]: unknown;
            };
            ingest: {
                [key: string]: string;
            };
            proxmox: {
                [key: string]: unknown;
            };
            scale_sets: {
                [key: string]: unknown;
            }[] | null;
            version: string;
        };
        Step: {
            /** Format: date-time */
            completed_at?: string;
            conclusion?: string;
            name: string;
            /** Format: int64 */
            number: number;
            /** Format: date-time */
            started_at?: string;
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-environments": {
        parameters: {
            query?: {
                /** @description Comma-separated states */
                state?: string;
                scale_set?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List-environmentsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-environment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "destroy-environment": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "read-logs": {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
                stream: "control-plane" | "runtime" | "agent" | "runner" | "job" | "metrics";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Read-logsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-events": {
        parameters: {
            query?: {
                after?: number;
                environment?: string;
                job?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List-eventsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-jobs": {
        parameters: {
            query?: {
                status?: string;
                scale_set?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List-jobsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-job": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-job-github": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetails"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-scale-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List-scale-setsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "job-stats": {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job-statsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
